name: "Print KmmBridge version"

runs:
  using: "composite"
  steps:
    - uses: touchlab/read-property@0.1
      id: versionPropertyValue
      with:
        file: ./gradle.properties
        property: LIBRARY_VERSION

    - name: Print versionPropertyValue
      id: output
      run: echo "${{ steps.versionPropertyValue.outputs.propVal }}"
