name: "Clone code and set up Java"

runs:
  using: "composite"
  steps:
    - name: "Clone code"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: "Set up Adopt OpenJDK 17"
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 17
