name: "Lint and build code"

on:
  push:
    branches:
      - "**"
      - "!main"

env:
  PUBLISH_GITHUB_USERNAME: ${{ secrets.PUBLISH_GITHUB_USERNAME }}
  PUBLISH_GITHUB_PASSWORD: ${{ secrets.PUBLISH_GITHUB_PASSWORD }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Lint code"
        uses: ./.github/actions/lint

  build:
    needs: lint
    runs-on: macos-latest
    steps:
      - name: "Clone code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Set up Adopt OpenJDK 17"
        uses: ./.github/actions/java
      - name: "Validate Gradle wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Build code"
        shell: sh
        run: sh gradlew build
