name: "Lint and build code, and publish artifacts to repository"

on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

permissions:
  contents: write
  packages: write

jobs:
  build_and_publish:
    runs-on: macos-latest
    steps:
      - name: "Clone code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: touchlab/read-property@0.1
        id: versionPropertyValue
        with:
          file: ./gradle.properties
          property: LIBRARY_VERSION # The release version. Defined in gradle.properties.

      - name: "Print versionPropertyValue"
        id: output
        run: echo "${{ steps.versionPropertyValue.outputs.propVal }}"

      - name: "Set up Adopt OpenJDK 17"
        uses: ./.github/actions/java

      - name: "Setup Gradle"
        uses: gradle/actions/setup-gradle@v4

      - name: "Create or Find Artifact Release"
        id: devrelease
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: "${{ steps.versionPropertyValue.outputs.propVal }}"

      - name: "Publish"
        shell: sh
        run: |
          sh gradlew publishKotlinMultiplatformPublicationToGitHubPackagesRepository publishAndroidReleasePublicationToGitHubPackagesRepository kmmBridgePublish \
            -PGITHUB_ARTIFACT_RELEASE_ID=${{ steps.devrelease.outputs.id }} \
            -PENABLE_PUBLISHING=true \
            -PGITHUB_PUBLISH_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -PGITHUB_REPO=${{ github.repository }} \
            --no-daemon \
            --info \
            --stacktrace

      # The GitHub Release hosts the Xcode binary, but we need to query GitHub for the URL after the binary is uploaded,
      # then generate the Package.swift file. Once that is committed, we need to point the release tag at the final commit.
      - uses: touchlab/ga-update-release-tag@v1
        id: update-release-tag
        with:
          commitMessage: "KMP SPM package release for ${{ steps.versionPropertyValue.outputs.propVal }}"
          tagMessage: "KMP release version ${{ steps.versionPropertyValue.outputs.propVal }}"
          tagVersion: ${{ steps.versionPropertyValue.outputs.propVal }}
