name: Publish
on:
  create:
    tags:
      - '^[0-9]+\.[0-9]+\.[0-9]+$'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Adopt OpenJDK 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Run Detekt
        shell: sh
        run: |
          sh gradlew --no-daemon detekt
      - name: Run KtLint
        shell: sh
        run: |
          sh gradlew --no-daemon ktlintCheck
      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_ACCESS_TOKEN_READ_PACKAGES: ${{ secrets.ACCESS_TOKEN_READ_PACKAGES }}
        shell: sh
        run: |
          sh gradlew publishAllPublicationsToAirthingsGitHubPackagesRepository
