name: "Lint and build code, and publish artifacts to repository"

on:
  push:
    branches:
      - "main"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Lint code"
        uses: ./.github/actions/lint

  build:
    needs: lint
    runs-on: macos-latest
    steps:
      - name: "Validate Gradle wrapper"
        uses: gradle/wrapper-validation-action@v1

  publish:
    needs: build
    permissions:
      contents: write
      packages: write
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildautoversion.yml@v1.1
    with:
      runsOn: "macOS-14"
      jvmVersion: 17
      versionBaseProperty: LIBRARY_VERSION
      publishTask: kmmBridgePublish publishAllPublicationsToGitHubPackagesRepository
    secrets:
      gradle_params: -PGITHUB_PUBLISH_USER=${{ secrets.GITHUB_ACTOR }} -PGITHUB_PUBLISH_TOKEN=${{ secrets.GITHUB_TOKEN }} -PGITHUB_REPO=https://github.com/Airthings/KmpLog.git
