name: Publish
on:
  create:
    tags:
      - '^[0-9]+\.[0-9]+\.[0-9]+$'
  push:
    branches:
      - publish-spm

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone repo"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Set up Adopt OpenJDK 17"
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
      - name: "Detekt"
        run: sh gradlew detekt
      - name: "KtLint"
        run: sh gradlew ktlintCheck

  build:
    needs: lint
    runs-on: macos-latest
    steps:
      - name: "Clone repo"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Set up Adopt OpenJDK 17"
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

  publish:
    needs: build
    permissions:
      contents: write
      packages: write
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildautoversion.yml@v1.1
    with:
      runsOn: "macOS-14"
      jvmVersion: 17
      versionBaseProperty: LIBRARY_VERSION
      publishTask: kmmBridgePublish publishAllPublicationsToGitHubPackagesRepository
    secrets:
      gradle_params: -PGITHUB_PUBLISH_USER=${{ secrets.GITHUB_ACTOR }} -PGITHUB_PUBLISH_TOKEN=${{ secrets.GITHUB_TOKEN }} -PGITHUB_REPO=https://github.com/Airthings/KmpLog.git
