name: "Lint and build code, and publish artifacts to repository"

on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  build_and_publish:
    needs: lint
    runs-on: macos-latest
    steps:
      - name: "Clone code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: touchlab/read-property@0.1
        id: versionPropertyValue
        with:
          file: ./gradle.properties
          property: LIBRARY_VERSION # The release version. Defined in gradle.properties.

      - name: "Print versionPropertyValue"
        id: output
        run: echo "${{ steps.versionPropertyValue.outputs.propVal }}"

      - name: "Set up Adopt OpenJDK 17"
        uses: ./.github/actions/java

      - name: "Setup Gradle"
        uses: gradle/actions/setup-gradle@v4

      - name: "Create or Find Artifact Release"
        id: devrelease
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: "${{ steps.versionPropertyValue.outputs.propVal }}"

      - name: "Publish"
        shell: sh"
        run: |
          pwd
          echo "Workspace: ${{ github.workspace }}"
          ls -l "${{ github.workspace }}/build/"
          sh gradlew kmmBridgePublish publishAllPublicationsToGitHubPackagesRepository \
            -PGITHUB_ARTIFACT_RELEASE_ID=${{ steps.devrelease.outputs.id }} \
            -PENABLE_PUBLISHING=true \
            -PGITHUB_PUBLISH_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -PGITHUB_REPO=${{ github.repository }}
            --no-daemon --info --stacktrace
